ARG arch=x64
FROM microsoft/aspnetcore:2.0 AS base
LABEL maintainer="synker-team@synker.ovh" \
      description="Notification broker service for Synker suite application" \
      system.dist="win" system.arch="$env" multi.name="Synker notification broker"
ARG arch
RUN echo $env:arch
# Step 6: Create user
RUN net user /add synker /fullname:"Synker Iptv"
# Step 7: Create Group
RUN net localgroup synkerGroup /add
RUN net localgroup synkerGroup synker /add
RUN net localgroup synkerGroup
USER synker:synkerGroup

#Expose Smtp and POP ports for mailing
EXPOSE 110:110
EXPOSE 587:587

WORKDIR /home/synker

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY *.sln ./
RUN ls
COPY ./Brokers/hfa.Notification.Brokers/hfa.Notification.Brokers.csproj hfa.Notification.Brokers/
COPY ./Brokers/hfa.Notification.DTo/hfa.Brokers.Messages.csproj hfa.Notification.DTo/
RUN dotnet restore
COPY . .
WORKDIR /src/Brokers/hfa.Notification.Brokers
RUN dotnet build -c Release -o /app -r win-$env:arch

FROM build AS publish
RUN dotnet publish -c Release -o /home/synker -r win-$env:arch

FROM base AS final
WORKDIR /home/synker
COPY --from=publish /home/synker .
Run ls -la
ENTRYPOINT ["dotnet", "hfa.Notification.Brokers.dll"]
#CMD ["v"] # TODO Add verbosity for example
