ARG arch=x64
FROM microsoft/aspnetcore:2.0 AS base
LABEL maintainer="synker-team@synker.ovh" \
      description="Notification broker service for Synker suite application" \
      system.dist="win" system.arch="$env" multi.name="Synker notification broker"

# Create Group and user
#RUN groupadd -r synker && useradd --no-log-init -r -g synker synker
RUN NET USER synker /add
RUN	NET LOCALGROUP Administrators /add synker
USER synker
RUN whoami
# add permissions for user and group

#Expose Smtp and POP ports for mailing
EXPOSE 110:110
EXPOSE 587:587

WORKDIR /home/synker

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY *.sln ./
COPY hfa.Notification.Brokers/hfa.Notification.Brokers.csproj hfa.Notification.Brokers/
COPY hfa.Notification.DTo/hfa.Brokers.Messages.csproj hfa.Notification.DTo/
RUN dotnet restore
COPY . .
WORKDIR /src/hfa.Notification.Brokers
RUN dotnet build -c Release -o /app -r win-$env:arch

FROM build AS publish
RUN dotnet publish -c Release -o /home/synker -r win-$env:arch

FROM base AS final
WORKDIR /home/synker
COPY --from=publish /home/synker .
Run ls -la
ENTRYPOINT ["dotnet", "hfa.Notification.Brokers.dll"]
#CMD ["v"] # TODO Add verbosity for example
