ARG arch=x64
FROM microsoft/dotnet:2.0-sdk AS build-env
LABEL maintainer="synker-team@synker.ovh" \
      description="Notification broker service for Synker suite application"
ARG arch
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ./hfa.Notification.Brokers/*.csproj .
RUN dotnet restore 

# Copy everything else and build
COPY . .
RUN dotnet publish ./hfa.Notification.Brokers/hfa.Notification.Brokers.csproj -r linux-$env:arch -c Release -o /out/
# Build runtime image
FROM microsoft/dotnet:2.0-runtime 
WORKDIR /app
COPY --from=build-env /out .
ENTRYPOINT ["dotnet", "hfa.Notification.Brokers.dll"]