// Generated by https://quicktype.io

export interface AboutApplication {
  Author:          string;
  ApplicationName: string;
  LastUpdate:      string;
  Comments:        null;
  Version:         string;
  License:         string;
  OSVersion:       OSVersion;
  EnvVersion:      Version;
}

export interface Version {
  Major:         number;
  Minor:         number;
  Build:         number;
  Revision:      number;
  MajorRevision: number;
  MinorRevision: number;
}

export interface OSVersion {
  Platform:      number;
  ServicePack:   string;
  Version:       Version;
  VersionString: string;
}
