namespace hfa.Synker.Service.Entities
{
    using MongoDB.Bson;
    using MongoDB.Bson.Serialization.Attributes;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class EntityBase : EntityBaseAudit
    {
        [Key]
        public int Id { get; set; }

        [BsonId]
        [NotMapped]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }
    }

    public class EntityBaseAudit
    {
        [BsonDateTimeOptions]
        public DateTime UpdatedDate { get; set; }
        [BsonDateTimeOptions]
        public DateTime CreatedDate { get; set; }
    }
}
