language: csharp
sudo: required
mono: none
dotnet: 2.0.0
dist: trusty
env:
  global:
    - CLI_VERSION: Latest
  matrix:
    - DOCKER_BUILD=true arch=x64
    #- DOCKER_BUILD=false arch=x64
os:
  - linux
#  - osx
branches:
  only:
    - /^\d\.\d\.\d$/
services:
  - docker
before_install:[
    "chmod +x travis-build.sh",
    "mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'\n"
  ]
script:
  - ./travis-build.sh $DOCKER_BUILD --quiet verify
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
cache:
  bundler: true
  directories:
    - $HOME/docker
    - node_modules
    - "~/.local/share/NuGet/Cache"
notifications: # set notification options
  email:
    recipients:
      - tunisienheni@gmail.com
    on_success: change
    on_failure: change