language: csharp
sudo: required
mono: none
dotnet: 2.0.0
dist: trusty
env:
  global:
    - CLI_VERSION: Latest
  matrix:
    - DOCKER_BUILD=true arch=x64
    #- DOCKER_BUILD=false arch=x64
os:
  - linux
#  - osx
branches:
  only:
    - master
    - /^tag-.*$/
services:
  - docker
before_install:
  - chmod +x travis-build.sh
script:
  - ./travis-build.sh $DOCKER_BUILD --quiet verify
cache:
  directories:
    - node_modules
    - "~/.local/share/NuGet/Cache"
notifications: # set notification options
  email:
    recipients:
      - tunisienheni@gmail.com
    on_success: change
    on_failure: change