language: csharp
sudo: required
mono: none
dotnet: 2.1.4
dist: trusty
environment:
  matrix:
    - CLI_VERSION: Latest
os:  
  - linux
#  - osx
branches:  
  only:
    - master
    - Develop
services:
  - docker
before_install:
  - chmod +x build.sh
script:
 - ./build.sh --quiet verify