language: minimal
sudo: required
mono: none
dotnet: 2.1.0
install: skip
if: (commit_message =~ ^build OR type = "cron") AND (branch = master)
matrix:
  - DOCKER_BUILD=true arch=x64
services:
  - docker
env:
  - DOCKERFILE_PATH=SynkerClient/Dockerfile PROJECT=webclient
  - DOCKERFILE_PATH=WebApi/Dockerfile PROJECT=webapi
  - DOCKERFILE_PATH=SyncLibrary/Dockerfile PROJECT=batch
os:
  - linux
#  - osx
before_install:
  - chmod +x trigger-build.sh
script:
  - export version=${TRAVIS_TAG:-"1.0.$TRAVIS_BUILD_NUMBER"}
  - echo "version => $version"
  - docker build -t "synker/${PROJECT}:${version}" -t "synker/${PROJECT}:latest" --build-arg version=$version -f $DOCKERFILE_PATH .
  - docker login -u=$DOCKER_USER -p=$DOCKER_PASS
  - docker push "synker/${PROJECT}"
jobs:
  include:
    stage: Trigger deploy Docker stack
    name: Deploy
    script:
    - chmod +x trigger-build.sh
    - if [[ -z "$TRAVIS_TAG" ]]; then version=$TRAVIS_TAG; else version="1.0.$TRAVIS_BUILD_NUMBER"; fi
    - export version=$TRAVIS_TAG
    - ./trigger-build.sh "Fazzani/synker-docker" $version
notifications: # set notification options
  email:
    recipients:
      - tunisienheni@gmail.com
    on_success: change
    on_failure: change