version: 4.5.0-beta{build}
image: Visual Studio 2017
configuration: Release
clone_folder: c:\projects\nlog
environment:
  github_auth_token:
    secure: +vzVo4DsD93fPeSkrIL12KQsq2VJrge4ZSt3KanSxtnifHsBXYmGko4Ck00sVOqD

install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"'

build_script:
  - ps: .\build.ps1
