version: 1.0.{build}.{branch}
image: Visual Studio 2017
configuration: Release
branches:
  only:
  - master
  - Develop
only_commits:
  message: /buildbrokerdocker:|builddocker:/
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
# environment variables
environment:
  ASPNETCORE_ENVIRONMENT: 'Production'
  DOCKER_USER:
    secure: i+Ljj6w996DAKfO+/Ozx9A==
  DOCKER_PASS:
    secure: t3JDT7lkxppxrNp9sRp2Cw==
  matrix:
   - version: win
     arch: x64
   - version: linux
     arch: x64
  #- version: 1.10-rc
  #  variant: nanoserver-sac2016
matrix:
  fast_finish: true
install:
  - docker version
  - ps: |
      [Environment]::SetEnvironmentVariable('dockerImage', ('synker/broker:{0}' -f $env:version), [EnvironmentVariableTarget]::Process);
      [Environment]::SetEnvironmentVariable('buildDirectory', ('{0}/windows/{1}' -f $env:version, $env:arch), [EnvironmentVariableTarget]::Process);
before_build:
  - cmd: echo %dockerImage%:%buildDirectory%
  - ps: mkdir $env:buildDirectory
  - cmd: echo %version%-%arch%
  - cmd: dotnet --version
  - cmd: cp ./docker/broker/Dockerfile-%version%-%arch% %buildDirectory%
  - ls -la
build_script:
  - cmd: appveyor-retry docker build -f %buildDirectory%/Dockerfile-%version%-%arch% -t %dockerImage% -t synker/broker:latest %buildDirectory%
after_build:
  - ps: docker images
#test_script:
#  - ps: docker run --rm $env:dockerImage
deploy_script:
  - docker login -u="%DOCKER_USER%" -p="%DOCKER_PASS%
  - docker push %dockerImage%  
  - docker push synker/broker:latest