version: 1.0.{build}.{branch}
image: Visual Studio 2017
configuration: Release
branches:
  only:
  - master
  - Develop
only_commits:
  message: /buildbrokerdocker:|builddocker:/
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
# environment variables
environment:
  ASPNETCORE_ENVIRONMENT: 'Production'
  DOCKER_USER:
    secure: i+Ljj6w996DAKfO+/Ozx9A==
  DOCKER_PASS:
    secure: BuN69UCJqbD6NYTCuYTdHw==
  matrix:
   - version: 1.9
     variant: windowsservercore-ltsc2016
  #- version: 1.9
  #  variant: nanoserver-sac2016
  #- version: 1.8
  #  variant: windowsservercore-ltsc2016
  #- version: 1.8
  #  variant: nanoserver-sac2016
  #- version: 1.10-rc
  #  variant: windowsservercore-ltsc2016
  #- version: 1.10-rc
  #  variant: nanoserver-sac2016
matrix:
  fast_finish: true
install:
  - docker version
  - ps: |
      [Environment]::SetEnvironmentVariable('dockerImage', ('synker/broker:{0}' -f $env:version), [EnvironmentVariableTarget]::Process);
      [Environment]::SetEnvironmentVariable('buildDirectory', ('{0}/windows/{1}' -f $env:version, $env:variant), [EnvironmentVariableTarget]::Process);

before_build:
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: cd ./hfa.Notification.Brokers
build_script:
  - cmd: appveyor-retry docker build --label --pull -t %dockerImage% -t synker/broker:latest .
after_build:
  - ps: docker images
test_script:
  - ps: docker run --rm $env:dockerImage
deploy_script:
  - docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  - docker push $env:dockerImage