version: '1.0.{build}'
image: Visual Studio 2017
configuration: Release
branches:
  only:
  - master
  - Develop
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
# environment variables
environment:
  ASPNETCORE_ENVIRONMENT: 'Production'
matrix:
  fast_finish: true
before_build:
  - echo ------------ Publish Sync batch version %APPVEYOR_BUILD_NUMBER% ----------
  - echo Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: cd ./SyncLibrary
build_script:
  - cmd: dotnet publish -c %CONFIGURATION% -r linux-arm --verbosity m -o artifacts 
  - ls
artifacts:
 - path: artifacts\*.*
   name: SynkerBatch
   type: zip
test_script:
  - echo restore packages for our unit tests
  - cmd: cd ../hfa.synker.batch.test/
  - cmd: dotnet restore ./hfa.synker.batch.test.csproj --verbosity m
  - echo run the unit tests (requires changing into the test directory)
  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off