version: '1.0.{build}'
image: Visual Studio 2017
configuration: Release
branches:
  only:
  - master
  - Develop
only_commits:
  message: /buildbroker:|build:/
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
# environment variables
environment:
  ASPNETCORE_ENVIRONMENT: 'Production'
matrix:
  fast_finish: true
before_build:
  - echo ------------ Publish Sync batch version %APPVEYOR_BUILD_NUMBER% ----------
  - echo Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: cd ./Brokers/hfa.Notification.Brokers
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
  - cmd: dotnet publish -c %CONFIGURATION% -r linux-x64 --verbosity m -o artifacts 
  - ls
artifacts:
 - path: .\Brokers\hfa.Notification.Brokers\artifacts
   name: SynkerBroker
   type: zip
on_finish :
  # any cleanup in here
deploy:
  - provider: Environment
    name: Synker.broker PROD
    on:
      branch: Develop