version: '3.4'

services:
  hfa.webclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  
  hfa.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  
#  hfa.notification.brokers:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "80"
#  
#  hfa.synker.batch:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "80"
  