version: '3'

services:
  
  hfa.notification.brokers:
    depends_on:
      - haproxy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_SECRETS_ID=f934f0be-ac10-4dd6-b82f-d7aecb08f04b
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
