version: '3'

services:
  hfa.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

#  hfa.webclient:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "80"


  hfa.notification.brokers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  hfa.synker.batch:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

