version: '3.4'

services:
 
  hfa.webclient:
    image: synker/webclient:${version:-latest}
    build:
      context: .
      dockerfile: SynkerClient/Dockerfile
      args:
      - version:${version}
  
  hfa.webapi:
    image: synker/webapi:${version:-latest}
    build:
      context: .
      dockerfile: WebApi/Dockerfile
      args:
      - version:${version}
  
  hfa.synker.batch:
    image: synker/batch:${version:-latest}
    build:
      context: .
      dockerfile: SyncLibrary/Dockerfile
      args:
      - version:${version}