ARG arch=x64
FROM microsoft/dotnet:2.0-sdk AS build-env
ARG arch
RUN echo $env:arch
WORKDIR /app

LABEL system.dist="win" system.arch="x64" multi.name="Synker notification broker"

# Copy csproj and restore as distinct layers
COPY ./hfa.Notification.Brokers/*.csproj .
RUN dotnet restore 

# Copy everything else and build
COPY . .
RUN dotnet publish ./hfa.Notification.Brokers/hfa.Notification.Brokers.csproj -r win-$env:arch -c Release -o /out/
# Build runtime image
FROM microsoft/dotnet 
WORKDIR /app
COPY --from=build-env /out .
ENTRYPOINT ["dotnet", "hfa.Notification.Brokers.dll"]