import { NgModule } from '@angular/core';
import {
    MdButtonModule,
    MdMenuModule,
    MdToolbarModule,
    MdIconModule,
    MdCardModule,
    MdTableModule,
    MdTooltipModule,
    MdTabsModule,
    MdAutocompleteModule,
    MdButtonToggleModule,
    MdCheckboxModule,
    MdDatepickerModule,
    MdInputModule,
    MdLineModule,
    MdFormFieldModule,
    MdGridListModule,
    MdDialogModule,
    MdSelectModule,
    MdSliderModule,
    MdSnackBarModule,
    MdProgressBarModule,
    MdProgressSpinnerModule,
    MdPaginatorModule,
    MdExpansionModule

} from '@angular/material';

@NgModule({
    imports: [
        MdButtonModule,
        MdMenuModule,
        MdToolbarModule,
        MdIconModule,
        MdCardModule,
        MdTableModule,
        MdTooltipModule,
        MdTabsModule,
        MdAutocompleteModule,
        MdButtonToggleModule,
        MdCheckboxModule,
        MdDatepickerModule,
        MdInputModule,
        MdLineModule,
        MdFormFieldModule,
        MdGridListModule,
        MdDialogModule,
        MdSelectModule,
        MdSliderModule,
        MdSnackBarModule,
        MdProgressBarModule,
        MdProgressSpinnerModule,
        MdIconModule,
        MdIconModule,
        MdPaginatorModule,
        MdExpansionModule
    ],
    exports: [MdButtonModule,
        MdMenuModule,
        MdToolbarModule,
        MdIconModule,
        MdCardModule,
        MdTableModule,
        MdTooltipModule,
        MdTabsModule,
        MdAutocompleteModule,
        MdButtonToggleModule,
        MdCheckboxModule,
        MdDatepickerModule,
        MdInputModule,
        MdLineModule,
        MdFormFieldModule,
        MdGridListModule,
        MdDialogModule,
        MdSelectModule,
        MdSliderModule,
        MdSnackBarModule,
        MdProgressBarModule,
        MdProgressSpinnerModule,
        MdIconModule,
        MdPaginatorModule,
        MdExpansionModule
    ]
})
export class AppModuleMaterialModule {
}